# Generated by Django 4.2.1 on 2023-05-16 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_balance_earnings_alter_balance_pending_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='core.normaluser'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normal_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
