# Generated by Django 4.2.1 on 2023-05-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_homeservice_seller'),
        ('core', '0004_alter_balance_user_alter_normaluser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.area'),
        ),
    ]
