# Generated by Django 4.2.1 on 2023-05-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_homeservice_categories_and_more'),
        ('core', '0007_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.SET_DEFAULT, to='services.area'),
        ),
    ]
