# Generated by Django 4.2.1 on 2023-05-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_homeservice_average_ratings_orderservice_end_service'),
        ('core', '0010_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='bio',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.area'),
        ),
    ]
