# Generated by Django 4.2.1 on 2023-05-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_normaluser_bio_alter_user_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='average_fast_answer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
