# Generated by Django 4.2.1 on 2023-05-19 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_normaluser_average_fast_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='earnings',
        ),
    ]
