# Generated by Django 4.2.1 on 2023-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_balance_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='average_fast_answer',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
