# Generated by Django 4.2.1 on 2023-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_normaluser_average_fast_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('client', 'buyer'), ('seller', 'seller_buyer')], max_length=50),
        ),
    ]
