# Generated by Django 4.2.1 on 2023-05-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_homeservice_categories_homeservice_categories'),
        ('core', '0015_alter_user_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='services.area'),
        ),
    ]
