# Generated by Django 4.2.1 on 2023-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
