# Generated by Django 4.2.1 on 2023-05-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_normaluser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_tries',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='next_confirm_try',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resend_tries',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
