# Generated by Django 4.2.1 on 2023-05-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_confirmation_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmation_code_sent_at',
            new_name='next_confirmation_code_sent',
        ),
    ]
