# Generated by Django 4.2.1 on 2023-06-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='pending_balance',
        ),
    ]
