# Generated by Django 4.2.1 on 2023-06-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_alter_earnings_beneficiary_alter_inputdata_field'),
        ('core', '0024_alter_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_area', to='services.area'),
        ),
    ]
