# Generated by Django 4.2.1 on 2023-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
