# Generated by Django 4.2.1 on 2023-07-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_user_forget_password_code"),
        ("core", "0031_alter_user_area"),
    ]

    operations = []
