# Generated by Django 4.2.1 on 2023-07-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_user_gender"),
        ("core", "0032_merge_20230701_1258"),
    ]

    operations = []
