# Generated by Django 4.2.1 on 2023-07-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_merge_0028_alter_user_gender_0032_merge_20230701_1258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normaluser",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
