# Generated by Django 4.2.1 on 2023-07-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_normaluser_bio"),
        ("core", "0034_alter_normaluser_bio"),
    ]

    operations = []
