# Generated by Django 4.2.1 on 2023-07-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20230704_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_confirmation_tries',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='forget_next_confirm_try',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
