# Generated by Django 4.2.1 on 2023-05-16 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_user_gender_alter_user_photo_normaluser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('minimum_price', models.PositiveIntegerField()),
                ('number_of_served_clients', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='categories', to='services.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.normaluser')),
                ('service_area', models.ManyToManyField(related_name='area_set', to='services.area')),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('description_message', models.CharField(max_length=1000)),
                ('answer_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='core.normaluser')),
                ('home_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_service', to='services.homeservice')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_of_service', models.IntegerField()),
                ('commitment_to_deadline', models.IntegerField()),
                ('work_ethics', models.IntegerField()),
                ('client_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('seller_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.orderservice')),
            ],
        ),
    ]
