# Generated by Django 4.2.1 on 2023-05-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_balance_user_alter_normaluser_user'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='core.normaluser'),
        ),
    ]
