# Generated by Django 4.2.1 on 2023-05-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_homeservice_average_fast_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='homeservice',
            name='average_fast_answer',
        ),
        migrations.CreateModel(
            name='PendingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.orderservice')),
            ],
        ),
    ]
