# Generated by Django 4.2.1 on 2023-05-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicesprice_remove_homeservice_average_fast_answer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesPrice',
            new_name='GeneralServicesPrice',
        ),
    ]
