# Generated by Django 4.2.1 on 2023-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_generalservicesprice_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalservicesprice',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
