# Generated by Django 4.2.1 on 2023-05-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_generalservicesprice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='status',
            field=models.CharField(choices=[('Underway', 'Underway'), ('Expire', 'Expire'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Underway', max_length=50),
        ),
    ]
