# Generated by Django 4.2.1 on 2023-05-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_orderservice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeservice',
            name='categories',
        ),
        migrations.AddField(
            model_name='homeservice',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_services_categories', to='services.category'),
        ),
    ]
