# Generated by Django 4.2.1 on 2023-05-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_homeservice_categories_homeservice_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='status',
            field=models.CharField(choices=[('Underway', 'Underway'), ('Expire', 'Expire'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
