# Generated by Django 4.2.1 on 2023-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_orderservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='categories'),
        ),
    ]
