# Generated by Django 4.2.1 on 2023-05-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_category_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeservice',
            old_name='minimum_price',
            new_name='average_price_per_hour',
        ),
    ]
