# Generated by Django 4.2.1 on 2023-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_rename_minimum_price_homeservice_average_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeservice',
            name='minimum_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
