# Generated by Django 4.2.1 on 2023-05-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_homeservice_minimum_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeservice',
            name='minimum_price',
        ),
    ]
