# Generated by Django 4.2.1 on 2023-05-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_homeservice_minimum_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeservice',
            old_name='categories',
            new_name='category',
        ),
    ]
