# Generated by Django 4.2.1 on 2023-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_rename_categories_homeservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeservice',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='homeservice',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
