# Generated by Django 4.2.1 on 2023-06-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_homeservice_description_alter_homeservice_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('TEXT', 'TEXT'), ('NUMBER', 'NUMBER')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='home_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_home_service', to='services.homeservice'),
        ),
        migrations.DeleteModel(
            name='PendingBalance',
        ),
        migrations.AddField(
            model_name='inputdata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.inputfield'),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='form',
            field=models.ManyToManyField(related_name='home_service_form', to='services.inputfield'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='form_data',
            field=models.ManyToManyField(related_name='order_form_data', to='services.inputdata'),
        ),
    ]
