# Generated by Django 4.2.1 on 2023-06-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_inputfield_note_alter_inputfield_field_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_services_categories', to='services.category'),
        ),
    ]
