# Generated by Django 4.2.1 on 2023-06-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_alter_earnings_beneficiary_alter_inputdata_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeservice',
            name='form',
        ),
        migrations.AddField(
            model_name='inputfield',
            name='home_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.homeservice'),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number')], default='TEXT', max_length=50),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
