# Generated by Django 4.2.1 on 2023-06-11 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_remove_homeservice_form_inputfield_home_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfield',
            name='home_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.homeservice'),
        ),
    ]
