# Generated by Django 4.2.1 on 2023-06-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_alter_inputfield_home_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_data', to='services.inputfield'),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='home_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='services.homeservice'),
        ),
    ]
