# Generated by Django 4.2.1 on 2023-06-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_alter_inputdata_field_alter_inputfield_home_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderservice',
            name='description_message',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='form_data',
        ),
        migrations.AddField(
            model_name='inputdata',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.orderservice'),
        ),
    ]
