# Generated by Django 4.2.1 on 2023-06-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_remove_orderservice_description_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.orderservice'),
        ),
    ]
