# Generated by Django 4.2.1 on 2023-06-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_inputdata_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_data_set', to='services.orderservice'),
        ),
    ]
