# Generated by Django 4.2.1 on 2023-06-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_earnings_created_date_alter_inputdata_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
