# Generated by Django 4.2.1 on 2023-06-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_orderservice_expected_time_by_day_to_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='expected_time_by_day_to_finish',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
