# Generated by Django 4.2.1 on 2023-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_alter_orderservice_expected_time_by_day_to_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='expected_time_by_day_to_finish',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
