# Generated by Django 4.2.1 on 2023-06-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_alter_rating_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='commitment_to_deadline',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='quality_of_service',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='work_ethics',
            field=models.FloatField(),
        ),
    ]
