# Generated by Django 4.2.1 on 2023-06-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_alter_rating_commitment_to_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='order_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='services.orderservice'),
        ),
    ]
