# Generated by Django 4.2.1 on 2023-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_alter_rating_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
