# Generated by Django 4.2.1 on 2023-07-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_alter_rating_rating_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfield',
            name='is_newest',
            field=models.BooleanField(default=True),
        ),
    ]
